name: One Piece - Mail Alert

on:
  schedule:
    # esegue ogni 4 ore (al minuto 27)
    - cron: "27 */4 * * *"
  workflow_dispatch:

jobs:
  mail-alert:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      MONGODB_DB: ${{ secrets.MONGODB_DB }}
      MONGODB_ACCOUNT_URI: ${{ secrets.MONGODB_ACCOUNT_URI }}
      MONGODB_ACCOUNT_DB: ${{ secrets.MONGODB_ACCOUNT_DB }}
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
      MAIL_FROM: ${{ secrets.MAIL_FROM }}
      GAME: "ONE PIECE"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymongo python-dotenv

      - name: Run Queue Price Alert script
        run: |
          python -m src.mail.priceAlert

      - name: Run Monthly Collection Report script
        run: |
          python -m src.mail.monthlyCollectionReport

      - name: Run Queue Stamp Alert script
        run: |
          python -m src.mail.stampAlert
