name: Run Ingestor

on:
  workflow_dispatch:

jobs:
  run-batches:
    runs-on: ubuntu-24.04

    # ⬇⬇⬇ QUI: env del JOB (vale per tutti gli steps del job)
    env:
      PYTHONUNBUFFERED: 1
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      MONGODB_DB: ${{ secrets.MONGODB_DB }}
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
      MAIL_FROM: ${{ secrets.MAIL_FROM }}
      MAIL_SUBJECT: "[Ingestor] Report"

      # modulo providers privato
      PROVIDERS_MODULE: private_providers.bundle

      # === PRIMARY (segrete) ===
      PRIMARY_URL_TEMPLATE: ${{ secrets.PRIMARY_URL_TEMPLATE }}
      PRIMARY_REFERER_TEMPLATE: ${{ secrets.PRIMARY_REFERER_TEMPLATE }}
      PRIMARY_HEADER_TEMPLATE: ${{ secrets.PRIMARY_HEADER_TEMPLATE }}

      # === SECONDARY (segrete) ===
      SECONDARY_LABEL_MAP: ${{ secrets.SECONDARY_LABEL_MAP }}
      SECONDARY_SELECTORS: ${{ secrets.SECONDARY_SELECTORS }}

      # === Cardmarket + FX (segrete) ===
      CM_PRICEGUIDE_URL: ${{ secrets.CM_PRICEGUIDE_URL }}
      FX_API_URL: ${{ secrets.FX_API_URL }}

      # tuning già presenti
      PRICES_BATCH: 500
      MONGO_PAGE_SIZE: 200
      SAMPLE_LIMIT: 0
      RATE_PER_SEC: 1.2
      BURST: 10

    steps:
      - uses: actions/checkout@v4

      # checkout della repo PRIVATA dei providers
      - uses: actions/checkout@v4
        with:
          repository: gregorysirtoli/OPCG_Script_Private # DOVE prendere il codice privato
          token: ${{ secrets.PROVIDERS_TOKEN }} # PAT con accesso a quella repo
          path: private_providers

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: python -m pip install -r requirements.txt

      - name: Run shard
        run: python -m src.ingest.main --shard-index "0" --shard-total "1"
